[package]
name = "rust_markdown_lsp"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ 
  "parser"
]

[dependencies]
ariadne = "0.5.0"
log = "0.4.26"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
simplelog = "0.12.2"
str_indices = "0.4.4"
parser = { path = "./parser/" }
walkdir = "2.5.0"
