[package]
name = "rust_markdown_lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9.3"
log = "0.4.26"
nom = "8.0.0"
ropey = "1.6.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
simplelog = "0.12.2"
