[package]
name = "rust_markdown_lsp"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ 
    "crates/parser",
    "crates/lsp_types", 
]
resolver = "2"

[workspace.dependencies]
ariadne = "0.5.0"
chumsky = "0.10.1"
log = "0.4.26"
lsp_types = { path = "./crates/lsp_types", version = "0.1.0" }
miette = "7.5.0"
parser = { path = "./crates/parser", version = "0.1.0" }
ropey = "1.6.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"
simplelog = "0.12.2"
str_indices = "0.4.4"
walkdir = "2.5.0"

[dependencies]
ariadne = { workspace = true }
log = { workspace = true }
lsp_types = { workspace = true }
miette = { workspace = true }
parser = { workspace = true }
ropey = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
simplelog = { workspace = true }
str_indices = { workspace = true }
walkdir = { workspace = true }

[[bin]]
name = "rust_markdown_lsp"
path = "src/main.rs"
bench = false
